### ISSUE TITLE
[Feature request] Macromedia Director 6.0

### ISSUE THREAD

**Issue by LoneDev6** [tomysshadow/Movie-Restorer-Xtra#1]
Would be nice to get Macromedia Director 6.0 compatibility.
Right now I get these errors and Director closes itself:
![error](https://i.imgur.com/6ar2csP.png)
![error](https://i.imgur.com/MGLKEaz.png)

Or maybe I'm doing something wrong?

**Comment by tomysshadow** [comment]
Movie Restorer currently only supports Director 8.0 and newer. I could add support for Director 7, but Director 5/6 predate Director API which Movie Restorer hooks to allow Director to open protected files.

You could always just use Director 8 and upgrade the movie to that version if all you would like to do is export cast members.

**Comment by LoneDev6** [comment]
> 
> 
> Movie Restorer currently only supports Director 8.0 and newer. I could add support for Director 7, but Director 5/6 predate Director API which Movie Restorer hooks to allow Director to open protected files.
> 
> You could always just use Director 8 and upgrade the movie to that version if all you would like to do is export cast members.

Thanks for the answer.
Well, what I want is to be able to open the .dcr and .cct files, edit images and export files back to the original game folder, so I don't think it's possible to use Director 8 files in a Direcot 6 game, right?

**Comment by tomysshadow** [comment]
No, but there are alternate approaches to do something like that.

Generally speaking, it's a bad idea to open a movie using Movie Restorer then publish it as a protected file again. Shockwave format uses lossy compression, which means if you publish back to a DCR type file, all the assets in that file will lose quality as they've been compressed twice.

The best approach to do something like this is to use a "proxy wrapper." Here's the idea:
1) rename your game file from example.dcr to example_.dcr
2) create your own example.dcr with the same width/height, colour palette etc. (you can look at the original example.dcr with Movie Restorer in a newer Director version to find these properties)
3) create a script in your example.dcr which goes to example_.dcr, then imports a file into the cast member you want to replace, like so:

```
on exitFrame me
  go(1, "example_.dcr")
  -- now we are in the scope of the original movie
  importFileInto(member("memberName"), "example.bmp")
end
```

Tada! Now the image will be replaced and without even modifying any of the original game files. :)

**Comment by LoneDev6** [comment]
> 
> 
> No, but there are alternate approaches to do something like that.
> 
> Generally speaking, it's a bad idea to open a movie using Movie Restorer then publish it as a protected file again. Shockwave format uses lossy compression, which means if you publish back to a DCR type file, all the assets in that file will lose quality as they've been compressed twice.
> 
> The best approach to do something like this is to use a "proxy wrapper." Here's the idea:
> 
>     1. rename your game file from example.dcr to example_.dcr
> 
>     2. create your own example.dcr with the same width/height, colour palette etc. (you can look at the original example.dcr with Movie Restorer in a newer Director version to find these properties)
> 
>     3. create a script in your example.dcr which goes to example_.dcr, then imports a file into the cast member you want to replace, like so:
> 
> 
> ```
> on exitFrame me
>   go(1, "example_.dcr")
>   -- now we are in the scope of the original movie
>   importFileInto(member("memberName"), "example.bmp")
> end
> ```
> 
> Tada! Now the image will be replaced and without even modifying any of the original game files. :)

If that works you're the one :D

**Comment by LoneDev6** [comment]
Would this work also with .cct files?

**Comment by tomysshadow** [comment]
If the cast file is statically linked by the movie, yes. You'd just create a proxy wrapper for the movie which loads the cast file, then specify the cast when using importFileInto

`importFileInto(member "memberName" of castLib 2, "example.bmp")`

The one issue you might run into, is you might have to copy the frame labels from the movie you're replacing, if the game goes to particular frame labels in that movie, e.g.

```
      if _movie.frameLabel = 0 then
        go(1, "login013_.dcr")
      else
        go(_movie.frameLabel, "login013_.dcr")
      end if
```

I know this technique works, I've used it for other games before (such as RobotRage: Rearmed)

**Comment by tomysshadow** [comment]
Out of curiousity, which game are you modifying? I might be able to help you

**Comment by LoneDev6** [comment]
Thanks a lot, it's interesting how you can hack Director using... Director.
Well, right now I'm working on hooking GDI32.DLL calls of the Projector as I have 0 experience on Director, because I really have no idea how to implement your explaination..

if you have Discord or other messaging app I can send your the files you need, it's a really old game

**Comment by LoneDev6** [comment]
Discord: LoneDev#7444

**Comment by LoneDev6** [comment]
Hello!
Was this implemented or rejected?
Thank you for your hard work

**Comment by tomysshadow** [comment]
This was closed because I have no intention of supporting Director 6. I
simply forgot to close it at the time.
