### ISSUE TITLE
Windows 98 and Director 8.5 usage

### ISSUE THREAD

**Issue by goodolvic** [tomysshadow/Movie-Restorer-Xtra#2]
I'm attempting to open a DCR using Director 8.5 within Windows 98 (VM) specifically. The Movie Restorer.x32 file is located within C:\Program Files\Macromedia\Director 8.5\Xtras.

When I go to the Xtras menu in Director, Movie Restorer isn't available. Is there anything special I may need to do to get it to appear? I have verified this setup works in Windows 7/Director MX 2004, so I'm wondering if it doesn't cooperate with such an old version of Windows.

**Comment by goodolvic** [comment]
Er, problem solved. The xtra was simply missing. Restoring the file to that location fixed it.

**Comment by tomysshadow** [comment]
It is Director 8.5 compatible, however the oldest supported Windows version
is Windows XP. You could install Director 8.5 on a newer Windows version,
use Movie Restorer to save the movie, and then open the movie on Windows 98
if that is a requirement.
